<?php $placeholder = htmlspecialchars(trim($this->getPlaceholder())); ?>
<input type='text' name='<?php echo $this->getFieldName() ?>' id='<?php echo $this->getFieldId() ?>'
       class='<?php echo $this->getFieldClass() ?>' style='<?php echo $this->getFieldStyle() ?>'
       value="<?php echo htmlspecialchars($this->getFieldValue()); ?>"
       <?php if ($this->getField()->getHideLabel()) { ?>aria-label="<?php echo $this->getField()->getName() ?>"
    <?php } else { ?> aria-labelledby="label_<?php echo $this->getFieldId() ?>" <?php } ?>
       <?php if ($this->getField()->getRequired()) { ?>aria-required="true"<?php } ?>
       <?php if ($this->getField()->getBrowserAutocomplete()) { ?>autocomplete="<?php echo $this->getField()->getBrowserAutocomplete() ?>" <?php } ?>
       <?php if ($this->getField()->getType() == 'email'){ ?>onkeyup="if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}"<?php } ?>
    <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?>
       placeholder="<?php echo $placeholder ?>" <?php echo htmlspecialchars($this->getField()->getCustomAttributes()) ?>
/>
<script type="text/javascript">
    require(["jquery","VladimirPopov_WebForms/js/colpick"], function ($) {
        $(document).ready(function (e) {
            var el = $("#<?php echo $this->getFieldId() ?>");
            el.css("background-color","#<?php echo htmlspecialchars($this->getFieldValue()); ?>");
            el.colpick({
                layout:"hex",
                submit:0,
                color: "#<?php echo htmlspecialchars($this->getFieldValue()); ?>",
                onChange:function(hsb,hex,rgb,el,bySetColor) {
                    $(el).css("background-color","#"+hex);
                    if(!bySetColor) $(el).val(hex);
                }
            }).keyup(function(){
                $(this).colpickSetColor(this.value);
            });
        });
    });
</script>
