<input type='password' name='<?php echo $this->getFieldName() ?>' id='<?php echo $this->getFieldId() ?>'
       class='<?php echo $this->getFieldClass() ?>' style='<?php echo $this->getFieldStyle() ?>'
       value="<?php echo htmlspecialchars($this->getFieldValue()) ?>"
       <?php if ($this->getField()->getHideLabel()) { ?>aria-label="<?php echo $this->getField()->getName() ?>"
    <?php } else { ?> aria-labelledby="label_<?php echo $this->getFieldId() ?>" <?php } ?>
       <?php if($this->getField()->getBrowserAutocomplete()) { ?>autocomplete="<?php echo $this->getField()->getBrowserAutocomplete()?>" <?php }?>
       <?php if ($this->getField()->getRequired()) { ?>aria-required="true"<?php } ?>
    <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?> <?php echo htmlspecialchars($this->getField()->getCustomAttributes())?>/>
